---
version: 2
plan:
  project-key: RCTJS1
  key: RCTPL1
  name: ReactJS-Plan1
  description: Build frontend application
stages:
- Default Stage:
    manual: false
    final: false
    jobs:
    - ReactJS1
ReactJS1:
  key: JOB1
  tasks:
  - checkout:
      force-clean-build: 'false'
      description: Checkout Default Repository
  - any-task:
      plugin-key: com.atlassian.bamboo.plugins.bamboo-nodejs-plugin:task.builder.npm
      configuration:
        isolatedCache: 'false'
        runtime: Node.js Path 14-03-2022
        command: install
      description: Node.JS install (It will create node_modules folder)
  - any-task:
      plugin-key: com.atlassian.bamboo.plugins.bamboo-nodejs-plugin:task.builder.npm
      configuration:
        isolatedCache: 'false'
        runtime: Node.js
        command: run build
      description: Node.JS run build (It will create build folder)
  - script:
      interpreter: BINSH_OR_CMDEXE
      scripts:
      - cp -R package.json /var/bamboo/bamboo-home/local-working-dir/RCTJS1-RCTPL1-JOB1/build/
      description: Copying Package.json file to /build folder
  - script:
      interpreter: SHELL
      scripts:
      - npm publish --registry https://vigneshmeganathan.jfrog.io/artifactory/api/npm/viky2204-npm-local/ -f build/
      description: Publish npm build on Jfrog artifacts
  artifact-subscriptions: []
repositories:
- GIT_Repository:
    scope: global
triggers:
- polling:
    period: '180'
branches:
  create: manually
  delete: never
  link-to-jira: true
notifications: []
labels: []
dependencies:
  require-all-stages-passing: false
  enabled-for-branches: true
  block-strategy: none
  plans: []
other:
  concurrent-build-plugin: system-default
---
version: 2
plan:
  key: RCTJS1-RCTPL1
plan-permissions:
- roles:
  - logged-in
  - anonymous
  permissions:
  - view
- users:
  - vigneshwar
  permissions:
  - view
  - edit
  - build
  - clone
  - admin
  - view_configuration
...

