---
version: 2
plan:
  project-key: MARS
  key: RCTPUL
  name: React-Pull-Yaml
stages:
  - Stage-Publish:
    - React-JS-Jfrog

React-JS-Jfrog:
   tasks:
     - script:
         interpreter: SHELL
         scripts:
          - npm pack calculator
         description: Pull npm artifacts from Jfrog repository step 2
     - script:
         interpreter: BINSH_OR_CMDEXE
         scripts:
           - tar -xvf calculator-0.1.2.tgz
         description: Extract tar.gz file
     - script:
         interpreter: SHELL
         scripts:
           - npm i -f package/
         description: Install the node_modules
